resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: false
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          2s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 100
        record-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException


    instances:
      tracking:
        base-config: default

  retry:
    configs:
      default:
        max-attempts: 2
        wait-duration:
          1000
        retry-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException

    instances:
      tracking:
        max-attempts: 3
